sudo: required
services:
  - docker

before_install:
 - docker build -t gauravjain449/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true gauravjain449/react-test npm test

after_success:
 - docker build -t gauravjain449/multi-client ./client
 - docker build -t gauravjain449/multi-nginx ./nginx
 - docker build -t gauravjain449/multi-server ./server
 - docker build -t gauravjain449/multi-worker ./worker

 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

 - docker push gauravjain449/multi-client
 - docker push gauravjain449/multi-nginx
 - docker push gauravjain449/multi-server
 - docker push gauravjain449/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-south-1
  app:  multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-south-1-852513569089
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  
