version: '3'
services:
  postgres:
    image: 'postgres:alpine'
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: 'redis:alpine'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    # volumes:
    #   - /app/node_modules
    #   - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    depends_on:
      - postgres
  client:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./client
    # volumes:
    #   - /app/node_modules
    #   - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile
      context: ./worker
    # volumes:
    #   - /app/node_modules
    #   - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  pgdata:
    external: false
    
        
        
